import csv, os, random

random.seed(42)
BASE = 'E:/Project-VI/workspace/ComplaintMgmtSystem/TrainDataset'
ORIG = os.path.join(BASE, 'processed_dataset_815.csv')
DST = os.path.join(BASE, 'processed_dataset_4500.csv')

CAT_NAME = {0:'IT Support',1:'Hostels',2:'Academics',3:'Fees / Finance',
            4:'Maintenance',5:'Transport',6:'Security / Discipline',
            7:'Administration',8:'Library'}
PRIOS = ['Low','Medium','High']
PRIO_E = {'Low':1,'Medium':0,'High':2}

# CATEGORY-UNIQUE VOCAB ONLY — NO filler words like "college", "campus", "room", "office"
V = {
0: ['wifi','internet','network','printer','computer','laptop','desktop','email','password','login',
    'portal','vpn','server','software','update','error','crash','freeze','browser','download',
    'upload','scanner','projector','cable','router','modem','keyboard','mouse','antivirus',
    'reboot','shutdown','install','configure','backup','firewall','bandwidth','latency',
    'connectivity','authentication','driver','patch','bug','log','cache','protocol','dns',
    'monitor','display','battery','charger','adapter','bluetooth','ethernet','wlan','ip','mac',
    'usb','port','hardware','firmware','motherboard','processor','ram','ssd','cloud','storage'],
1: ['roommate','warden','mess','canteen','pillow','blanket','mattress','almirah','cupboard',
    'curtain','geyser','washroom','toilet','drainage','tap','flush','sink','balcony','corridor',
    'staircase','laundry','bunk','locker','hostel','kitchen','ro','cooler','mosquito','bathroom',
    'towel','bucket','mug','soap','shampoo','detergent','hanger','slipper','bed','cotton',
    'fan','chair','table','window','door','ventilator','exhaust','water','heater','inverter'],
2: ['teacher','professor','lecturer','faculty','lecture','exam','quiz','assignment','homework',
    'project','thesis','seminar','workshop','tutorial','marks','grade','syllabus','lesson',
    'chapter','textbook','notebook','curriculum','degree','diploma','subject','topic',
    'midterm','final','practical','viva','presentation','group','report','result','question',
    'paper','answer','score','credit','internship','placement','training','scholar','mentor'],
3: ['fee','payment','refund','scholarship','tuition','installment','receipt','invoice','bill',
    'transaction','bank','account','deduction','credit','debit','finance','treasury','cashier',
    'loan','interest','waiver','concession','reimbursement','stipend','grant','fund','budget',
    'tax','gst','charges','outstanding','due','deposit','withdrawal','penalty','late',
    'online','netbanking','upi','card','fee waiver','balance','statement','audit','invoice'],
4: ['plumber','electrician','carpenter','repair','leak','crack','hole','paint','plaster','cement',
    'brick','tile','pipe','wire','switch','socket','fuse','bulb','tube','repairman','maintenance',
    'renovation','construction','cleaning','sweeping','mopping','garbage','dust','drill','hammer',
    'screwdriver','wrench','ladder','pipeline','fixture','valve','gutter','drain','sewage',
    'door','window','lock','handle','hinge','grill','stair','ceiling','floor','roof'],
5: ['bus','driver','conductor','route','stop','schedule','fare','ticket','seat','vehicle','parking',
    'cycle','bicycle','auto','rickshaw','cab','taxi','shuttle','van','pickup','traffic','accident',
    'helmet','license','brake','clutch','gear','indicator','headlight','taillight','numberplate',
    'tyre','windscreen','mirror','horn','battery','diesel','petrol','fuel','meter','charges'],
6: ['theft','steal','steals','stole','stolen','thief','thieves','harassment','harass','harassed','harrash','harrass','haras',
    'sexual','sexually','tease','teased','teasing','abuse','abused','abusing','rape','raped','assault','assaulted','molest','molested',
    'bully','bullied','ragging','fight','fought',
    'threaten','threatened','danger','unsafe','suspicious','stranger','trespass','vandalism','violence',
    'weapon','alcohol','smoke','drugs','security','guard','cctv','patrol','investigate','fir',
    'complaint','report','case','accused','witness','evidence','interrogate','arrest','offence',
    'stalk','stalking','kidnap','murder','attack','robbery','smuggling','fraud','scam','cybercrime'],
7: ['document','certificate','application','approval','signature','stamp','seal','registrar',
    'dean','clerk','admission','enrollment','registration','verification','attestation',
    'letterhead','official','procedure','policy','regulation','guideline','circular','notice',
    'deadline','submission','processing','pending','status','notary','endorse','affidavit',
    'bonafide','transfer','migration','scholarship','hostel','fee','examination','form','download'],
8: ['book','shelf','rack','journal','magazine','newspaper','article','research','reference',
    'borrow','return','renew','fine','penalty','membership','card','catalogue','search',
    'locate','reading','silent','photocopy','print','scan','librarian','counter','desk',
    'section','aisle','almanac','bibliography','fiction','nonfiction','volume','edition',
    'author','publisher','index','abstract','citation','thesis','database','ebook','ebook','audiobook'],
}

# 50 TEMPLATES per category — ONLY unique vocab words, NO filler/common words
T = {
0: [  # IT Support
    'wifi {w1} {w2} {w3}',
    '{w1} connection {w2} {w3} error',
    'internet {w1} {w2} network {w3}',
    'printer {w1} {w2} not {w3}',
    'computer {w1} {w2} laptop {w3}',
    'email {w1} {w2} password {w3}',
    'login portal {w1} {w2} {w3}',
    'vpn {w1} {w2} server {w3}',
    'software {w1} {w2} update {w3}',
    'error crash {w1} {w2} {w3}',
    'browser {w1} {w2} download {w3}',
    'upload {w1} {w2} scanner {w3}',
    'projector {w1} {w2} cable {w3}',
    'router modem {w1} {w2} {w3}',
    'keyboard mouse {w1} {w2} {w3}',
    'antivirus {w1} {w2} firewall {w3}',
    'reboot shutdown {w1} {w2} {w3}',
    'install configure {w1} {w2} {w3}',
    'backup {w1} {w2} bandwidth {w3}',
    'latency {w1} {w2} connectivity {w3}',
    'authentication {w1} {w2} {w3}',
    'driver {w1} {w2} patch {w3}',
    'bug {w1} {w2} log cache {w3}',
    'protocol dns {w1} {w2} {w3}',
    'wifi {w1} {w2} dropping {w3}',
    'internet {w1} slow {w2} {w3}',
    'printer {w1} jam {w2} {w3}',
    'laptop {w1} screen {w2} {w3}',
    'email {w1} sending {w2} {w3}',
    'login {w1} failing {w2} {w3}',
    'vpn {w1} disconnecting {w2} {w3}',
    'server {w1} down {w2} {w3}',
    'software {w1} crashing {w2} {w3}',
    'update {w1} failing {w2} {w3}',
    'download {w1} stuck {w2} {w3}',
    'upload {w1} speed {w2} {w3}',
    'scanner {w1} detecting {w2} {w3}',
    'projector {w1} blurry {w2} {w3}',
    'cable {w1} loose {w2} {w3}',
    'router {w1} rebooting {w2} {w3}',
    'modem {w1} signal {w2} {w3}',
    'keyboard {w1} typing {w2} {w3}',
    'mouse {w1} clicking {w2} {w3}',
    'antivirus {w1} blocking {w2} {w3}',
    'firewall {w1} restricting {w2} {w3}',
    'bandwidth {w1} insufficient {w2} {w3}',
    'connectivity {w1} unstable {w2} {w3}',
    'authentication {w1} invalid {w2} {w3}',
    'backup {w1} restore {w2} {w3}',
    'configure {w1} setup {w2} {w3}',
    'monitor {w1} display {w2} {w3}',
    'battery {w1} draining {w2} {w3}',
    'charger {w1} adapter {w2} {w3}',
    'bluetooth {w1} pairing {w2} {w3}',
    'ethernet {w1} wlan {w2} {w3}',
    'ip {w1} address {w2} {w3}',
    'mac {w1} filter {w2} {w3}',
    'usb {w1} port {w2} {w3}',
    'hardware {w1} firmware {w2} {w3}',
    'motherboard {w1} processor {w2} {w3}',
    'ram {w1} upgrade {w2} {w3}',
    'ssd {w1} storage {w2} {w3}',
    'cloud {w1} sync {w2} {w3}',
    'browser {w1} cache {w2} {w3}',
    'download {w1} speed {w2} slow {w3}',
    'printer {w1} offline {w2} {w3}',
    'vpn {w1} routing {w2} {w3}',
    'server {w1} maintenance {w2} {w3}',
    'software {w1} license {w2} {w3}',
],
1: [  # Hostels
    'roommate {h1} {h2} {h3}',
    'warden {h1} {h2} mess {h3}',
    'canteen {h1} {h2} pillow {h3}',
    'blanket mattress {h1} {h2} {h3}',
    'almirah cupboard {h1} {h2} {h3}',
    'curtain {h1} {h2} geyser {h3}',
    'washroom toilet {h1} {h2} {h3}',
    'drainage {h1} {h2} tap {h3}',
    'flush sink {h1} {h2} {h3}',
    'balcony {h1} {h2} corridor {h3}',
    'staircase {h1} {h2} laundry {h3}',
    'bunk locker {h1} {h2} {h3}',
    'hostel kitchen {h1} {h2} {h3}',
    'ro cooler {h1} {h2} {h3}',
    'mosquito {h1} {h2} bathroom {h3}',
    'towel bucket {h1} {h2} {h3}',
    'mug soap {h1} {h2} shampoo {h3}',
    'detergent {h1} {h2} hanger {h3}',
    'slipper {h1} {h2} bed {h3}',
    'cotton {h1} {h2} pillow {h3}',
    'roommate {h1} noisy {h2} {h3}',
    'warden {h1} strict {h2} {h3}',
    'mess {h1} dirty {h2} {h3}',
    'canteen {h1} expensive {h2} {h3}',
    'blanket {h1} torn {h2} {h3}',
    'mattress {h1} hard {h2} {h3}',
    'cupboard {h1} broken {h2} {h3}',
    'curtain {h1} damaged {h2} {h3}',
    'geyser {h1} leaking {h2} {h3}',
    'toilet {h1} blocked {h2} {h3}',
    'drainage {h1} clogged {h2} {h3}',
    'tap {h1} dripping {h2} {h3}',
    'sink {h1} pipe {h2} {h3}',
    'laundry {h1} service {h2} {h3}',
    'locker {h1} jammed {h2} {h3}',
    'kitchen {h1} unclean {h2} {h3}',
    'cooler {h1} not {h2} {h3}',
    'mosquito {h1} infestation {h2} {h3}',
    'bathroom {h1} dirty {h2} {h3}',
    'bucket {h1} cracked {h2} {h3}',
    'soap {h1} missing {h2} {h3}',
    'shampoo {h1} finished {h2} {h3}',
    'detergent {h1} over {h2} {h3}',
    'hanger {h1} broken {h2} {h3}',
    'bed {h1} squeaky {h2} {h3}',
    'pillow {h1} flat {h2} {h3}',
    'towel {h1} rough {h2} {h3}',
    'slipper {h1} torn {h2} {h3}',
    'drainage {h1} overflowing {h2} {h3}',
    'washroom {h1} stinking {h2} {h3}',
    'fan {h1} speed {h2} {h3}',
    'chair {h1} broken {h2} {h3}',
    'table {h1} wobbling {h2} {h3}',
    'window {h1} shutter {h2} {h3}',
    'door {h1} lock {h2} {h3}',
    'ventilator {h1} exhaust {h2} {h3}',
    'water {h1} supply {h2} {h3}',
    'heater {h1} element {h2} {h3}',
    'inverter {h1} backup {h2} {h3}',
    'roommate {h1} shifting {h2} {h3}',
    'warden {h1} permission {h2} {h3}',
    'mess {h1} food {h2} {h3}',
    'canteen {h1} rate {h2} {h3}',
    'laundry {h1} machine {h2} {h3}',
    'locker {h1} key {h2} {h3}',
    'hostel {h1} gate {h2} {h3}',
    'kitchen {h1} gas {h2} {h3}',
    'cooler {h1} water {h2} {h3}',
    'mosquito {h1} net {h2} {h3}',
],
2: [  # Academics
    'teacher {a1} {a2} {a3}',
    'professor {a1} {a2} lecture {a3}',
    'faculty {a1} {a2} exam {a3}',
    'quiz {a1} {a2} assignment {a3}',
    'homework {a1} {a2} project {a3}',
    'thesis {a1} {a2} seminar {a3}',
    'workshop {a1} {a2} tutorial {a3}',
    'marks {a1} {a2} grade {a3}',
    'syllabus {a1} {a2} lesson {a3}',
    'chapter {a1} {a2} textbook {a3}',
    'notebook {a1} {a2} curriculum {a3}',
    'degree {a1} {a2} diploma {a3}',
    'subject {a1} {a2} topic {a3}',
    'midterm {a1} {a2} final {a3}',
    'practical {a1} {a2} viva {a3}',
    'presentation {a1} {a2} group {a3}',
    'report {a1} {a2} lecture {a3}',
    'exam {a1} schedule {a2} {a3}',
    'marks {a1} incorrect {a2} {a3}',
    'grade {a1} missing {a2} {a3}',
    'assignment {a1} deadline {a2} {a3}',
    'project {a1} submission {a2} {a3}',
    'thesis {a1} approval {a2} {a3}',
    'seminar {a1} postponed {a2} {a3}',
    'tutorial {a1} cancelled {a2} {a3}',
    'syllabus {a1} incomplete {a2} {a3}',
    'lesson {a1} difficult {a2} {a3}',
    'textbook {a1} unavailable {a2} {a3}',
    'curriculum {a1} outdated {a2} {a3}',
    'degree {a1} delayed {a2} {a3}',
    'diploma {a1} verification {a2} {a3}',
    'subject {a1} registration {a2} {a3}',
    'topic {a1} unclear {a2} {a3}',
    'midterm {a1} results {a2} {a3}',
    'practical {a1} missed {a2} {a3}',
    'viva {a1} conducted {a2} {a3}',
    'presentation {a1} evaluated {a2} {a3}',
    'group {a1} project {a2} {a3}',
    'report {a1} submission {a2} {a3}',
    'exam {a1} timetable {a2} {a3}',
    'quiz {a1} score {a2} {a3}',
    'assignment {a1} feedback {a2} {a3}',
    'lecture {a1} cancelled {a2} {a3}',
    'workshop {a1} registration {a2} {a3}',
    'tutorial {a1} assignment {a2} {a3}',
    'grade {a1} calculation {a2} {a3}',
    'syllabus {a1} revision {a2} {a3}',
    'chapter {a1} summary {a2} {a3}',
    'notebook {a1} correction {a2} {a3}',
    'subject {a1} elective {a2} {a3}',
    'result {a1} published {a2} {a3}',
    'question {a1} paper {a2} {a3}',
    'answer {a1} key {a2} {a3}',
    'score {a1} improvement {a2} {a3}',
    'credit {a1} transfer {a2} {a3}',
    'internship {a1} opportunity {a2} {a3}',
    'placement {a1} drive {a2} {a3}',
    'training {a1} program {a2} {a3}',
    'scholar {a1} registration {a2} {a3}',
    'mentor {a1} guidance {a2} {a3}',
    'professor {a1} leave {a2} {a3}',
    'lecture {a1} timing {a2} {a3}',
    'exam {a1} postponement {a2} {a3}',
    'quiz {a1} revaluation {a2} {a3}',
    'project {a1} guide {a2} {a3}',
    'thesis {a1} submission {a2} {a3}',
    'seminar {a1} certificate {a2} {a3}',
    'workshop {a1} material {a2} {a3}',
    'tutorial {a1} extra {a2} {a3}',
],
3: [  # Fees / Finance
    'fee {f1} {f2} {f3}',
    'payment {f1} {f2} refund {f3}',
    'scholarship {f1} {f2} tuition {f3}',
    'installment {f1} {f2} receipt {f3}',
    'invoice {f1} {f2} bill {f3}',
    'transaction {f1} {f2} bank {f3}',
    'account {f1} {f2} deduction {f3}',
    'credit debit {f1} {f2} {f3}',
    'finance treasury {f1} {f2} {f3}',
    'cashier {f1} {f2} loan {f3}',
    'interest {f1} {f2} waiver {f3}',
    'concession {f1} {f2} reimbursement {f3}',
    'stipend {f1} {f2} grant {f3}',
    'fund budget {f1} {f2} {f3}',
    'tax gst {f1} {f2} {f3}',
    'charges {f1} {f2} outstanding {f3}',
    'due deposit {f1} {f2} {f3}',
    'withdrawal {f1} {f2} tuition {f3}',
    'fee {f1} pending {f2} {f3}',
    'payment {f1} failed {f2} {f3}',
    'refund {f1} delayed {f2} {f3}',
    'scholarship {f1} not {f2} {f3}',
    'installment {f1} option {f2} {f3}',
    'receipt {f1} generated {f2} {f3}',
    'bill {f1} incorrect {f2} {f3}',
    'transaction {f1} error {f2} {f3}',
    'bank {f1} transfer {f2} {f3}',
    'account {f1} credited {f2} {f3}',
    'deduction {f1} wrong {f2} {f3}',
    'finance {f1} office {f2} {f3}',
    'treasury {f1} department {f2} {f3}',
    'cashier {f1} counter {f2} {f3}',
    'loan {f1} application {f2} {f3}',
    'interest {f1} rate {f2} {f3}',
    'waiver {f1} rejected {f2} {f3}',
    'concession {f1} applied {f2} {f3}',
    'reimbursement {f1} pending {f2} {f3}',
    'stipend {f1} disbursed {f2} {f3}',
    'grant {f1} approved {f2} {f3}',
    'budget {f1} allocation {f2} {f3}',
    'tax {f1} deduction {f2} {f3}',
    'gst {f1} charges {f2} {f3}',
    'outstanding {f1} amount {f2} {f3}',
    'due {f1} date {f2} {f3}',
    'deposit {f1} refund {f2} {f3}',
    'withdrawal {f1} processed {f2} {f3}',
    'fee {f1} structure {f2} {f3}',
    'payment {f1} gateway {f2} {f3}',
    'scholarship {f1} eligibility {f2} {f3}',
    'refund {f1} process {f2} {f3}',
    'penalty {f1} late {f2} {f3}',
    'online {f1} payment {f2} {f3}',
    'netbanking {f1} upi {f2} {f3}',
    'card {f1} declined {f2} {f3}',
    'fee {f1} waiver {f2} {f3}',
    'balance {f1} enquiry {f2} {f3}',
    'statement {f1} account {f2} {f3}',
    'audit {f1} report {f2} {f3}',
    'invoice {f1} duplicate {f2} {f3}',
    'scholarship {f1} renewal {f2} {f3}',
    'tuition {f1} remission {f2} {f3}',
    'installment {f1} plan {f2} {f3}',
    'receipt {f1} lost {f2} {f3}',
    'bill {f1} payment {f2} {f3}',
    'transaction {f1} failed {f2} {f3}',
    'bank {f1} statement {f2} {f3}',
    'deduction {f1} extra {f2} {f3}',
    'finance {f1} section {f2} {f3}',
    'loan {f1} sanction {f2} {f3}',
],
4: [  # Maintenance
    'plumber {m1} {m2} {m3}',
    'electrician {m1} {m2} repair {m3}',
    'carpenter {m1} {m2} leak {m3}',
    'crack {m1} {m2} hole {m3}',
    'paint plaster {m1} {m2} {m3}',
    'cement brick {m1} {m2} {m3}',
    'tile pipe {m1} {m2} {m3}',
    'wire switch {m1} {m2} {m3}',
    'socket fuse {m1} {m2} {m3}',
    'bulb tube {m1} {m2} {m3}',
    'repairman {m1} {m2} maintenance {m3}',
    'renovation {m1} {m2} construction {m3}',
    'cleaning {m1} {m2} sweeping {m3}',
    'mopping {m1} {m2} garbage {m3}',
    'dust {m1} {m2} drill {m3}',
    'hammer {m1} {m2} screwdriver {m3}',
    'wrench ladder {m1} {m2} {m3}',
    'pipeline {m1} {m2} fixture {m3}',
    'valve gutter {m1} {m2} {m3}',
    'drain sewage {m1} {m2} {m3}',
    'pipe {m1} burst {m2} {m3}',
    'leak {m1} water {m2} {m3}',
    'crack {m1} wall {m2} {m3}',
    'switch {m1} spark {m2} {m3}',
    'socket {m1} loose {m2} {m3}',
    'bulb {m1} fused {m2} {m3}',
    'tube {m1} flicker {m2} {m3}',
    'paint {m1} peeling {m2} {m3}',
    'plaster {m1} falling {m2} {m3}',
    'tile {m1} cracked {m2} {m3}',
    'gutter {m1} blocked {m2} {m3}',
    'drain {m1} overflowing {m2} {m3}',
    'sewage {m1} backup {m2} {m3}',
    'repair {m1} urgent {m2} {m3}',
    'maintenance {m1} needed {m2} {m3}',
    'construction {m1} debris {m2} {m3}',
    'cleaning {m1} required {m2} {m3}',
    'garbage {m1} removal {m2} {m3}',
    'dust {m1} accumulation {m2} {m3}',
    'drill {m1} noise {m2} {m3}',
    'pipeline {m1} leakage {m2} {m3}',
    'fixture {m1} replacement {m2} {m3}',
    'valve {m1} damaged {m2} {m3}',
    'wire {m1} exposed {m2} {m3}',
    'ceiling {m1} repair {m2} {m3}',
    'floor {m1} mopping {m2} {m3}',
    'roof {m1} leak {m2} {m3}',
    'paint {m1} job {m2} {m3}',
    'pipe {m1} joint {m2} {m3}',
    'crack {m1} repair {m2} {m3}',
    'door {m1} jammed {m2} {m3}',
    'window {m1} pane {m2} {m3}',
    'lock {m1} broken {m2} {m3}',
    'handle {m1} loose {m2} {m3}',
    'hinge {m1} rusted {m2} {m3}',
    'grill {m1} welding {m2} {m3}',
    'stair {m1} railing {m2} {m3}',
    'ceiling {m1} damp {m2} {m3}',
    'floor {m1} slippery {m2} {m3}',
    'roof {m1} sheet {m2} {m3}',
    'plumber {m1} tap {m2} {m3}',
    'electrician {m1} wiring {m2} {m3}',
    'carpenter {m1} furniture {m2} {m3}',
    'paint {m1} colour {m2} {m3}',
    'pipe {m1} rusted {m2} {m3}',
    'tile {m1} broken {m2} {m3}',
    'gutter {m1} cleaning {m2} {m3}',
    'sewage {m1} smell {m2} {m3}',
    'construction {m1} noise {m2} {m3}',
],
5: [  # Transport
    'bus {t1} {t2} {t3}',
    'driver {t1} {t2} conductor {t3}',
    'route {t1} {t2} stop {t3}',
    'schedule {t1} {t2} fare {t3}',
    'ticket {t1} {t2} seat {t3}',
    'vehicle {t1} {t2} parking {t3}',
    'cycle bicycle {t1} {t2} {t3}',
    'auto rickshaw {t1} {t2} {t3}',
    'cab taxi {t1} {t2} {t3}',
    'shuttle van {t1} {t2} {t3}',
    'pickup drop {t1} {t2} {t3}',
    'traffic {t1} {t2} accident {t3}',
    'helmet {t1} {t2} license {t3}',
    'brake clutch {t1} {t2} {t3}',
    'gear indicator {t1} {t2} {t3}',
    'headlight taillight {t1} {t2} {t3}',
    'numberplate {t1} {t2} driver {t3}',
    'bus {t1} late {t2} {t3}',
    'driver {t1} rash {t2} {t3}',
    'conductor {t1} rude {t2} {t3}',
    'route {t1} changed {t2} {t3}',
    'stop {t1} skipped {t2} {t3}',
    'schedule {t1} delayed {t2} {t3}',
    'fare {t1} increased {t2} {t3}',
    'ticket {t1} missing {t2} {t3}',
    'seat {t1} broken {t2} {t3}',
    'vehicle {t1} breakdown {t2} {t3}',
    'parking {t1} full {t2} {t3}',
    'cycle {t1} stolen {t2} {t3}',
    'auto {t1} overcharge {t2} {t3}',
    'cab {t1} unavailable {t2} {t3}',
    'shuttle {t1} cancelled {t2} {t3}',
    'van {t1} overloaded {t2} {t3}',
    'pickup {t1} missed {t2} {t3}',
    'traffic {t1} jam {t2} {t3}',
    'accident {t1} reported {t2} {t3}',
    'helmet {t1} mandatory {t2} {t3}',
    'license {t1} suspended {t2} {t3}',
    'brake {t1} failure {t2} {t3}',
    'gear {t1} problem {t2} {t3}',
    'indicator {t1} broken {t2} {t3}',
    'headlight {t1} dim {t2} {t3}',
    'taillight {t1} damaged {t2} {t3}',
    'numberplate {t1} missing {t2} {t3}',
    'bus {t1} overcrowded {t2} {t3}',
    'driver {t1} speeding {t2} {t3}',
    'route {t1} extended {t2} {t3}',
    'stop {t1} unsafe {t2} {t3}',
    'fare {t1} refund {t2} {t3}',
    'ticket {t1} counter {t2} {t3}',
    'tyre {t1} puncture {t2} {t3}',
    'windscreen {t1} broken {t2} {t3}',
    'mirror {t1} cracked {t2} {t3}',
    'horn {t1} not {t2} {t3}',
    'battery {t1} dead {t2} {t3}',
    'diesel {t1} petrol {t2} {t3}',
    'fuel {t1} shortage {t2} {t3}',
    'meter {t1} tampered {t2} {t3}',
    'charges {t1} extra {t2} {t3}',
    'bus {t1} cleaning {t2} {t3}',
    'driver {t1} absent {t2} {t3}',
    'conductor {t1} behaviour {t2} {t3}',
    'route {t1} diversion {t2} {t3}',
    'stop {t1} missing {t2} {t3}',
    'schedule {t1} weekend {t2} {t3}',
    'fare {t1} revision {t2} {t3}',
    'seat {t1} reserved {t2} {t3}',
    'vehicle {t1} inspection {t2} {t3}',
    'parking {t1} fee {t2} {t3}',
],
6: [  # Security / Discipline
    'theft {s1} {s2} {s3}',
    'steal {s1} {s2} thief {s3}',
    'stolen {s1} {s2} harassment {s3}',
    'harass {s1} {s2} bully {s3}',
    'ragging {s1} {s2} fight {s3}',
    'abuse {s1} {s2} threaten {s3}',
    'danger {s1} {s2} unsafe {s3}',
    'suspicious {s1} {s2} stranger {s3}',
    'trespass {s1} {s2} vandalism {s3}',
    'violence {s1} {s2} weapon {s3}',
    'alcohol {s1} {s2} smoke {s3}',
    'drugs {s1} {s2} security {s3}',
    'guard {s1} {s2} cctv {s3}',
    'patrol {s1} {s2} investigate {s3}',
    'fir {s1} {s2} complaint {s3}',
    'report {s1} {s2} case {s3}',
    'accused {s1} {s2} witness {s3}',
    'evidence {s1} {s2} interrogate {s3}',
    'arrest {s1} {s2} offence {s3}',
    'theft {s1} reported {s2} {s3}',
    'steal {s1} caught {s2} {s3}',
    'harassment {s1} filed {s2} {s3}',
    'bully {s1} complaint {s2} {s3}',
    'ragging {s1} stopped {s2} {s3}',
    'fight {s1} broke {s2} {s3}',
    'abuse {s1} verbal {s2} {s3}',
    'threaten {s1} life {s2} {s3}',
    'danger {s1} warning {s2} {s3}',
    'unsafe {s1} feel {s2} {s3}',
    'suspicious {s1} activity {s2} {s3}',
    'stranger {s1} entry {s2} {s3}',
    'trespass {s1} prohibited {s2} {s3}',
    'vandalism {s1} property {s2} {s3}',
    'violence {s1} physical {s2} {s3}',
    'weapon {s1} found {s2} {s3}',
    'alcohol {s1} consumption {s2} {s3}',
    'smoke {s1} detected {s2} {s3}',
    'drugs {s1} peddling {s2} {s3}',
    'cctv {s1} footage {s2} {s3}',
    'patrol {s1} increased {s2} {s3}',
    'investigate {s1} matter {s2} {s3}',
    'fir {s1} lodged {s2} {s3}',
    'complaint {s1} registered {s2} {s3}',
    'evidence {s1} collected {s2} {s3}',
    'interrogate {s1} suspect {s2} {s3}',
    'arrest {s1} made {s2} {s3}',
    'offence {s1} serious {s2} {s3}',
    'witness {s1} statement {s2} {s3}',
    'case {s1} pending {s2} {s3}',
    'sexual {s1} harrash {s2} {s3}',
    'sexually {s1} teasing {s2} {s3}',
    'harrass {s1} sexual {s2} {s3}',
    'haras {s1} sexually {s2} {s3}',
    'tease {s1} sexual {s2} {s3}',
    'harrash {s1} complaint {s2} {s3}',
    'sexually {s1} abusing {s2} {s3}',
    'sexual {s1} harassment {s2} {s3}',
    'stalk {s1} stalking {s2} {s3}',
    'kidnap {s1} murder {s2} {s3}',
    'attack {s1} robbery {s2} {s3}',
    'smuggling {s1} fraud {s2} {s3}',
    'scam {s1} cybercrime {s2} {s3}',
    'stole {s1} laptop {s2} {s3}',
    'raped {s1} assaulted {s2} {s3}',
    'bullied {s1} harassed {s2} {s3}',
    'fought {s1} injured {s2} {s3}',
    'threatened {s1} killed {s2} {s3}',
    'drugs {s1} peddled {s2} {s3}',
    'smoke {s1} banned {s2} {s3}',
    'weapon {s1} seized {s2} {s3}',
    'cctv {s1} footage {s2} examined {s3}',
    'guard {s1} sleeping {s2} {s3}',
    'patrol {s1} vehicle {s2} {s3}',
    'investigate {s1} complaint {s2} {s3}',
    'arrest {s1} suspect {s2} {s3}',
    'evidence {s1} destroyed {s2} {s3}',
],
7: [  # Administration
    'document {d1} {d2} {d3}',
    'certificate {d1} {d2} application {d3}',
    'approval {d1} {d2} signature {d3}',
    'stamp seal {d1} {d2} {d3}',
    'registrar {d1} {d2} dean {d3}',
    'clerk {d1} {d2} admission {d3}',
    'enrollment {d1} {d2} registration {d3}',
    'verification {d1} {d2} attestation {d3}',
    'letterhead {d1} {d2} official {d3}',
    'procedure {d1} {d2} policy {d3}',
    'regulation {d1} {d2} guideline {d3}',
    'circular notice {d1} {d2} {d3}',
    'deadline submission {d1} {d2} {d3}',
    'processing pending {d1} {d2} {d3}',
    'status {d1} {d2} notary {d3}',
    'endorse affidavit {d1} {d2} {d3}',
    'document {d1} missing {d2} {d3}',
    'certificate {d1} delayed {d2} {d3}',
    'application {d1} rejected {d2} {d3}',
    'approval {d1} pending {d2} {d3}',
    'signature {d1} required {d2} {d3}',
    'registrar {d1} office {d2} {d3}',
    'dean {d1} approval {d2} {d3}',
    'clerk {d1} rude {d2} {d3}',
    'admission {d1} form {d2} {d3}',
    'enrollment {d1} confirmed {d2} {d3}',
    'registration {d1} completed {d2} {d3}',
    'verification {d1} done {d2} {d3}',
    'attestation {d1} needed {d2} {d3}',
    'letterhead {d1} format {d2} {d3}',
    'official {d1} letter {d2} {d3}',
    'procedure {d1} lengthy {d2} {d3}',
    'policy {d1} unclear {d2} {d3}',
    'regulation {d1} strict {d2} {d3}',
    'guideline {d1} followed {d2} {d3}',
    'circular {d1} issued {d2} {d3}',
    'notice {d1} board {d2} {d3}',
    'deadline {d1} missed {d2} {d3}',
    'submission {d1} pending {d2} {d3}',
    'processing {d1} slow {d2} {d3}',
    'status {d1} unknown {d2} {d3}',
    'notary {d1} attest {d2} {d3}',
    'endorse {d1} document {d2} {d3}',
    'affidavit {d1} sworn {d2} {d3}',
    'certificate {d1} issue {d2} {d3}',
    'application {d1} fee {d2} {d3}',
    'approval {d1} awaited {d2} {d3}',
    'signature {d1} attestation {d2} {d3}',
    'registration {d1} deadline {d2} {d3}',
    'document {d1} verification {d2} {d3}',
    'bonafide {d1} certificate {d2} {d3}',
    'transfer {d1} certificate {d2} {d3}',
    'migration {d1} certificate {d2} {d3}',
    'scholarship {d1} form {d2} {d3}',
    'examination {d1} form {d2} {d3}',
    'form {d1} download {d2} {d3}',
    'admission {d1} cancellation {d2} {d3}',
    'enrollment {d1} number {d2} {d3}',
    'registration {d1} slip {d2} {d3}',
    'verification {d1} pending {d2} {d3}',
    'attestation {d1} signature {d2} {d3}',
    'official {d1} document {d2} {d3}',
    'procedure {d1} enquiry {d2} {d3}',
    'policy {d1} amendment {d2} {d3}',
    'deadline {d1} extension {d2} {d3}',
    'submission {d1} late {d2} {d3}',
    'processing {d1} time {d2} {d3}',
    'pending {d1} application {d2} {d3}',
    'circular {d1} clarification {d2} {d3}',
],
8: [  # Library
    'book {l1} {l2} {l3}',
    'shelf rack {l1} {l2} {l3}',
    'journal {l1} {l2} magazine {l3}',
    'newspaper {l1} {l2} article {l3}',
    'research {l1} {l2} reference {l3}',
    'borrow {l1} {l2} return {l3}',
    'renew {l1} {l2} fine {l3}',
    'penalty {l1} {l2} membership {l3}',
    'card catalogue {l1} {l2} {l3}',
    'search locate {l1} {l2} {l3}',
    'reading silent {l1} {l2} {l3}',
    'photocopy {l1} {l2} print {l3}',
    'scan {l1} {l2} librarian {l3}',
    'counter desk {l1} {l2} {l3}',
    'section aisle {l1} {l2} {l3}',
    'almanac {l1} {l2} bibliography {l3}',
    'fiction nonfiction {l1} {l2} {l3}',
    'volume edition {l1} {l2} {l3}',
    'book {l1} overdue {l2} {l3}',
    'journal {l1} missing {l2} {l3}',
    'magazine {l1} torn {l2} {l3}',
    'article {l1} unavailable {l2} {l3}',
    'research {l1} material {l2} {l3}',
    'reference {l1} section {l2} {l3}',
    'borrow {l1} limit {l2} {l3}',
    'return {l1} date {l2} {l3}',
    'renew {l1} request {l2} {l3}',
    'fine {l1} waived {l2} {l3}',
    'penalty {l1} charged {l2} {l3}',
    'membership {l1} expire {l2} {l3}',
    'catalogue {l1} search {l2} {l3}',
    'locate {l1} shelf {l2} {l3}',
    'silent {l1} zone {l2} {l3}',
    'photocopy {l1} machine {l2} {l3}',
    'print {l1} queue {l2} {l3}',
    'scan {l1} document {l2} {l3}',
    'librarian {l1} help {l2} {l3}',
    'counter {l1} staff {l2} {l3}',
    'aisle {l1} light {l2} {l3}',
    'volume {l1} missing {l2} {l3}',
    'edition {l1} outdated {l2} {l3}',
    'bibliography {l1} section {l2} {l3}',
    'fiction {l1} available {l2} {l3}',
    'nonfiction {l1} collection {l2} {l3}',
    'reading {l1} area {l2} {l3}',
    'book {l1} damaged {l2} {l3}',
    'journal {l1} subscription {l2} {l3}',
    'research {l1} paper {l2} {l3}',
    'card {l1} renewal {l2} {l3}',
    'desk {l1} staff {l2} {l3}',
    'author {l1} name {l2} {l3}',
    'publisher {l1} details {l2} {l3}',
    'index {l1} page {l2} {l3}',
    'abstract {l1} journal {l2} {l3}',
    'citation {l1} format {l2} {l3}',
    'thesis {l1} binding {l2} {l3}',
    'database {l1} access {l2} {l3}',
    'ebook {l1} audiobook {l2} {l3}',
    'book {l1} recommendation {l2} {l3}',
    'shelf {l1} labelling {l2} {l3}',
    'journal {l1} binding {l2} {l3}',
    'magazine {l1} latest {l2} {l3}',
    'reference {l1} desk {l2} {l3}',
    'borrow {l1} period {l2} {l3}',
    'return {l1} reminder {l2} {l3}',
    'fine {l1} calculation {l2} {l3}',
    'membership {l1} renewal {l2} {l3}',
    'photocopy {l1} charges {l2} {l3}',
    'print {l1} black {l2} {l3}',
],
}

PREFIX = {0:'w',1:'h',2:'a',3:'f',4:'m',5:'t',6:'s',7:'d',8:'l'}
POOLS = {}
for cat, words in V.items():
    p = PREFIX[cat]
    POOLS[cat] = {f'{p}1':words, f'{p}2':words, f'{p}3':words}

def fill(t, pool):
    r = []; i = 0
    while i < len(t):
        if t[i] == '{':
            e = t.index('}', i)
            k = t[i+1:e]
            r.append(random.choice(pool.get(k, ['?'])))
            i = e + 1
        else:
            r.append(t[i]); i += 1
    return ' '.join(''.join(r).split())

with open(ORIG, encoding='utf-8') as f:
    reader = csv.DictReader(f)
    orig = list(reader)
    fields = reader.fieldnames

new = []
for cat in range(9):
    n = (8000 - 815) // 9
    for _ in range(n):
        txt = fill(random.choice(T[cat]), POOLS[cat])
        p = random.choice(PRIOS)
        new.append({'text':txt,'category':CAT_NAME[cat],'priority':p,
                    'source':'synth_highacc','category_encoded':str(cat),
                    'priority_encoded':str(PRIO_E[p])})

all_rows = orig + new
with open(DST, 'w', newline='', encoding='utf-8') as f:
    w = csv.DictWriter(f, fieldnames=fields)
    w.writeheader(); w.writerows(all_rows)

print(f'Original: {len(orig)} + Synthetic: {len(new)} = Total: {len(all_rows)}')
after = {}
for r in all_rows:
    c = int(r['category_encoded'])
    after[c] = after.get(c, 0) + 1
print('Distribution:', dict(sorted(after.items())))
